'''
logo.py: Embedded icon for use in the "About" panel

The rest of this file was generated by using the img2py.py program that
is provided with wxPython 4.0, in the following sequence of commands:

  # Create a 200 pixel wide version of the logo
  cairosvg --output-width 200 -f png -o logo.png ../.graphics/bun-logo.svg

  # Generate logo.py
  img2py -f -i -n Logo logo.png logo.py

  # Clean up
  rm logo.png

The only changes to the output were to add the file header and this
explanatory comment.

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2019 by the California Institute of Technology.  This code is
open-source software released under a 3-clause BSD license.  Please see the
file "LICENSE" for more information.
'''

#----------------------------------------------------------------------
# This file was generated by /Users/mhucka/system/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Logo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAWCAYAAAChWZ5EAAAABmJLR0QA/wD/AP+gvaeTAAAC'
    b'eklEQVRIie2WTUhUURiGn+/MxGShRiSR5hQ6REQQs6hdadAPSbSzgiIQKlp4lRa1aNnS6Eer'
    b'TX+GQVEQNAQRiGhFQasWLfrXmUkLJFooZs4452vhOD9Xrymhs+ndnfe+93vec87iXmGW0sbK'
    b'coQajNmK1SqgDNEVID7QHyCDQB/CC4ztlov9A7OZKzNCnVAASewHHGDzbMum9Qb0MkO+e3I7'
    b'+tsrZDzhzcEjSCIGdEyBixxCxMl/gQ6w6wCbdsIgtyi1MW0OHlOPzU4xtbGyHCPXgTqvcsAT'
    b'kKWgNTneF6ATOOHxTifiPyqtvXHPAnoyWEWKLmBt2hoFimYo8jdFEL2ASjcTpz2ANTvkSvT9'
    b'ZCBzBWn4swxc+cry4mUIL7N1xQG96wHrQvQg2SsACKKmJodTgbE96gQ35BXQenykuAOszsKo'
    b'4OfwTZRwdp4tQc2SafHCYlRKyT/VMOhZV3Ilwn11QgEmw+qsOYVoi8fO/lHyGnQI2OkqfE5a'
    b'46dFnVAJJhFHKZ3j5BHQzyCbXH4EqAY2ptdNCH0oj125JP7xaoNJ1mfgwiDGhBHeusKjiG5B'
    b'tSfjqLajgW1AyrXjFpAHOUYbyqOc0leBMWARSX+DH9Xd2aEUY20tQpmrQABrahFdleXIcUju'
    b'Anz5UX0+1cusP6KBM0hiD1CFSJ1oU/AdsJ6FUyqn0Kgf+AqMLGCB/8qTqBOMI1QWiG8Nhk8F'
    b'goPSa7BEClYAjRjGxm8A/QWgD+Mz541c+/YL5ADg+dcyD7KINMil2HcDIG2xV6jZDkTnHS0M'
    b'orJPWmMPJ5Y5UicUwCQPY9mLaAiY/tM7d40hGsXKU4qK2qXlw/Dkgz/DIMtgryFhzQAAAABJ'
    b'RU5ErkJggg==')
getLogoData = Logo.GetData
getLogoImage = Logo.GetImage
getLogoBitmap = Logo.GetBitmap
getLogoIcon = Logo.GetIcon
