'''
logo.py: Embedded icon for use in the "About" panel

The rest of this file was generated by using the img2py.py program that
is provided with wxPython 4.0, in the following sequence of commands:

  # Create a 160 pixel wide version of the logo
  cairosvg --output-width 160 -f png -o logo.png ../.graphics/quiche-logo.svg

  # Generate logo.py
  img2py -f -i -n Logo logo.png logo.py

  # Clean up
  rm logo.png

The only changes to the output were to add the file header and this
explanatory comment.

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2019 by the California Institute of Technology.  This code is
open-source software released under a 3-clause BSD license.  Please see the
file "LICENSE" for more information.
'''

#----------------------------------------------------------------------
# This file was generated by /Users/mhucka/system/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Logo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAABmJLR0QA/wD/AP+gvaeTAAAg'
    b'AElEQVR4nM2deYBUxfHHP9Uze4CKgBARdt7sIgGVeETiLYqKAokxiQb9qVHxQo6dmV01XvFY'
    b'EzXGqOzOghi84pVDTTSJEUFFwXj/DPEWuXZnFySCnOouu/Ne/f7oN7Nz7aWY/Oqfxe7qruqa'
    b'ft3V36puhf8npFXl/XGTI0H2RGQXoD/CTkAJsB3lc2Az6FaElbQUfSTzVm3572oN8t8QqpER'
    b'JdB6KGKOAY4C9gF2/xJdrUN4H2UJqovYrd9rUvNe247Vtmv6jxlQq8v64AV+hOqZwDigbw7L'
    b'F8AyYAWwCdjsz7rtQAmGnVF2BQYA3wRGdtLHItCHCehfZFZzy9c3IktfuwE16owBmQl6CtDP'
    b'L/ZA30HkeTwWYYJvUbeqSUB73C8IseEhaD8AlWNBjgHdl9SYhC2oPoaaOVLfuHTHjwxfzNdE'
    b'GgmNRcxVoBM7CnkF0Qcoch+T29Zu2PEyhwzGFE1GOQvk0LRUmI/HTTI78dKOlrnDDaiVZfti'
    b'TB1wjF+0DeFO1LtL4s3Ls3hjwx28tgpUPsdr/VDuWP9Zj+VcNmoXvvhiFKI7YYpXS92qRHbf'
    b'FaPwkhcichGws1/8HEpU6hPvf5UxZtIOM6BOHdqX0uBlwJVAMbAVYS7Gu0VmNW/M4o05x6Pc'
    b'ABycUZwEXgWeRc0C1jW8IY/ipttMJsCQ8oMQbyLCeJRDgGDGUF4D/ZnEE89lyYqM6Adt0xEu'
    b'AwYCSYQ7KOlztdyybNtXHfcOMaBWlY/D8x4EygAXuIPW4DWF3AyNONci1FjZsh54H7QvsC9Q'
    b'msG6CXgXZS3CMGA0dgNJUSvwNkgLsA/oYEBRuVbqG2/IkzvdGUCx3IjqRYABTSCcJXVNS77K'
    b'2L+SAbUGw6fO1QjXAgGQ11Cmd7Zoa8y5HuVaoA2Rq/CKZkv9iu3gz+A+gbGoOQF0ErB3gS7e'
    b'R3U+sJCgvpjaZa1b1B5F9EagCLhe4omagjpUhr5DQOaifAdIInodA5pulhq8L2ODL21ArS4b'
    b'iGseAY4DXIQbWZv4eeZnl8UfdWqA64A2lB9LfeJvXfY/bc9vUJwcgTKEAB/jbl8h9evWd9km'
    b'GvoByKNAEcp1Up/4eUG+GoJsDNeAXgkYlAUkOV3mJjZ1P/Js+lIG1KrwHng8DbofyHrEO0vq'
    b'mhZ0yh91rgRuAtpBTpN44+NfRm6PdIuET0b0D1gjXiH1iV91ylsZPhajDwF7AO+j7gSpX9Pc'
    b'G3m9NqBWlu+FcReAOCBv43mTZHbT2oK8kRH9MG11KFMAF9Ezpa7pj72V2Wsdo6H/AXkICCD8'
    b'lpZgVWfHPo0MK4PA0wijgQYkMFHqVi/rqaxeGdAaT5f4C/aLGHOS1DZszuKZtuc3KGk/GtWJ'
    b'IKcBOwHbUJki9Y1/7rGsmDMZ5aeAAVbTOvgMmfdme8/bh09B9T5gF+Bz0D+CLKCt6AW5c+Un'
    b'Wbx2OfobcDjCJyTdsTJnzUc9kdNjA2pkWBliXrIzj6cIeD9OL+KVzhEY/SHIeGD/jH494Gkk'
    b'cHHur6pTh/alJPhdRCeCeVjijc9n1UedOBDx/7OFgFeW6Q7pjME7E+zzJ5RNwGPslnhCakhm'
    b'9RGrGIW6twMTsT8EgIK+DTyDJ0+knGtfnz8jTABWY+QIqW38uDu79MiAOnX4rpS2LwbZH/RV'
    b'itvGy63//lxjwx00+SAWEEjRZ8ASVF4gqH+SWYlVef3VYNjorALCftH9Ek9MyZY5poi+n47G'
    b'8wJ4+nHuMmF/0MAKLFoDIpdKXeNtBfWvdoaTlFMQHQeMxc7KlAkWI4GzpW5VQqvL+uCahcCR'
    b'wLu0c1R3G0u3BvRdlaf8XybdqV48NEQy+AYWRVmH6N248jSDEq/lzoSC/Uadx2xbfZx2ue/L'
    b'7IBWh8BkkMPxvOtldvM7PRhPkA3OIRiZBHqBr/+/CSYPktvXNtnJ4i6xGyRPEU+c2NUZvXsD'
    b'xkJXoXIjwicY70CZ1bwGQKPOs1gXZiGtwVP/P2BzmaQ1GDY5h+MVv5HyNfN4pg7fldLkI8AJ'
    b'wDMST5wA/hFTk28Cg0B+KvHGWzuT06UBNRY6CpXnAIPqJKlvWuiXH4TK68CntPPNzmaPv2Pf'
    b'B9Iu8cRRhXi+LtKY8xOUB0HfwpjTpbbxg4J8050BFLECGIiRMVLb+E+re3gSRv8OuHiM6wyI'
    b'MIUKwV9UVR4AgiC/TBnPp5Msk/62U+NFw4djvP+1qIj2K8TztZKYfwDLQfbH0xd1MoGCbHMT'
    b'm0DuB8DTk9LlsxvnA78Gghju1ynlpYXaBwsVAlAavAa7yL/Jx43XZdWpOd4uC/J05yPwBoP0'
    b'Ae6ntG8kt9aiJd7N4PVHZCHF2+Ny678/77y/nPaX7r4T7SUR4HiUTbjuVZmuh9Q2NOiMwQdS'
    b'1OdGVIKdnZAss7cAlWrgeKAmXd46+GpKP5kAsj/9vCuy6lJNCyo3c9hIAoG3gSLUHCH1Da+m'
    b'66rK++N5G4AkAW9AV6ivTikvld82tBasizofAHtlFK1BmCZ1iSc7HWiqbcT5PsJcYFhG8bsS'
    b'T+zbXduC/VkkaSMQoDU4KHM910jZwYh5BWhHAvvnumOFP2ETiGPdg3mZxgPA9cYCAVRf6Q4y'
    b'79R4NaOLscZzMfoj4HlgGMoTGnGiXQ426sQQHgeGISzy23vAaK3p4ovqSs95a78AXgOClLpH'
    b'ZNXVN78Oeh9Qgufekts2z4DW4kxA2ELA+1meNCOTbM/yQla7KeWlna0zeQrbwM+7QACPUuKJ'
    b'44DLAYNQp5HweYXaaSx8PlCLhcJ+Sl1iPK7ZyY5D3umJ+2TH6FyksVD2pib44/G+m9egyL0C'
    b'+Azh+xoJfzuzqsAMNNZonszJA0Iv3X0n0DMAxTPpM63GKkaxq7eOIeHHejIAq7D6mJ3cRlV4'
    b'iMQTtyBc5NfdqbHQQVmyI2UHozrX1stUiTfeSmVoD0StiyHeTT0Rq5WhoRYhl7/rzGEj0xUe'
    b'f8SGWs6048xQ9ba1G/wlQxC9KrMuy4BaWbYvwveBL2B7bZ70tuI6PzK2SGY3fAj+iUHd39ty'
    b'zYKbNDKsTKPOTRoLXaWxiuywZV3TI8CzwFBcfVKryvtLXeIuVG8DilCpVX+Ntn9NLRbru0Xq'
    b'Gu/R6c4AjDwJDAGe8fvrkD2jfIhGQz/TSPhGrS5Lr5X2RKO/A3YmELg7XV6feB/heaA/bcV1'
    b'eWNvN7cDLcDJGnH2KWhATGCatTJ352JvGnEuBzkf+AwjHbtq8b/3Ar4NrKRPn0s6+EeUIIEl'
    b'wJWo3Ih672g09K20wqAEvNOAZQgH4nkvaSS0J0G9BmgGDicaPgyASOhIhMNAE2w112l12QiK'
    b'eMmXu4x2Tss8LWisbD+C+jbIDYhehWsW69QxRR2DKZkO+ipoU9b4PSLAZyDn2/F2kNzRsA70'
    b'XsBg/C8l04B2YddT/Z7uyTJe1LkO4WbARTk30ymV2c3vIJyAuuOyYgym9QCgAlgNPGMRHHk6'
    b'azbMat6IuuNB3wL2QeQdXPk5yEpfj1GW0YzyW6xkF/cGXPM2sDfoW6g7PtMX1YuHhlAz30eM'
    b'FgINwJ6Urt8vLbd+xVaJNx0m8aYzs4xkZ+F5WID4Zh8EzjCEsXZROT31g3TMwE8/OxEYBCyV'
    b'uua3M4xXg/V/XIQpUp/IW+ekLvFMF0DkegYmvouyABhGMjA7W+k1zZT2HQtyH1AKcino0UA7'
    b'XuAVAAJq3Qg4BpFLLJ/eS2nfsXly24OzgaGIzmdg4nsINnzqaY+AE6lLPAqc4cu7TqNOGpCV'
    b'+salCO+ADqbP+gmQaUDRM6zFeCBVpJHw1aRgeGSy1CUe6okSALR472AjbfuzdmgxrpmCsAXR'
    b'H2rMOT5L6VuWbZN443nAQSC3A3djzAmpdVZmJd7Dk4mg94DMwtODJd50fm5UTSOhExBOAjZD'
    b'8Fw+GVyKsh/QzmeBd3uqusQTj/hYZhtwmW8HXwjWBipnQmqRnkyAPZwNQH+CSUduX9uk0fAx'
    b'oM9ikeQfS13TX3tsvJSsqLMEGAtyocQb79aIcznCzQh/l7rEib3tr1t5sdBTqExKQfkacy5E'
    b'mQeyWOKN4zptN3VMEUNbJTevRmOhk1B5DAhgzHFS2/CCVjvDcVkJfMrAxDfsDBxSNgboD/KR'
    b'3L7WX1j1eqxfdm2u8XQyAY0612ll+NguRyRyp9/iEp06poigdxfQgjJJp+35jYKDqQxX2Chb'
    b'gbrIiBKtDFcUrJtRPgSVCcAXJJmnNaOLUS62td6dXerZZ/3LbNz2Ua5cqWv6K6I1gMHzrgfw'
    b'8c0GYDc2l+9nDWiMNYTo83a4QwdhgcettCTjeQKHhCcCNZhsnyiPBuz8GMhHwF6UrL/Y+pWy'
    b'GDAUJQ/KZddqZzRGVyDti3Xq8F2z6qYO3xVpX4zRFZm7eZoC3kHYJekFmZvYxMZtl2BPO8sY'
    b'2K/rUIIiQBjax+fVtbi1wFbgKN8ugC4CwHOPNX4H/vHFGpD2YAopXu4fc7JJvJMte/ZpJI+t'
    b'5r02xIv6Kv5CY86JiH7oy/pm/kDMGmA16CGUJhemjOjjdgtBDwEaaJc1+cJS/cmHGgudBPwc'
    b'8FAqu095UxslFI7L63be2i9QVgDQVhSyhfK8r+/Y1CbiO4bBf1mGgJ+jIhnQd1a3JUALQf1d'
    b'14qB1DUtQPgFNsz4BMo5vrJrAbSqfJxGncVa7YyW2obNqDvOV/hgSpKLtDJcQam7AJsG0ogx'
    b'x8ncxCatLNtXo86LGik72hflQ/56LiqPA0GU66U+8Wx3OmICc1CdjZEHCtYL9msQ19pF1beT'
    b'7m387z4MJBnQdzWA//cz0BEaGTI4r8PWwedizNBC8Y6CVJeoQeRSbNrHAISX0OK/AOB5hwFH'
    b'4emvwXdrcI8BViIciNEP/Zm3imByrNQ2NNhBm1uBIyFg82u05HHgZWz6RztKdWeB9Tz71DZs'
    b'lvqmiNQ2/Cu3zv9sK4BttO5uZW8NrPDHMtwQbBuBTctYlZrq/t8lgEGKCkzrN9tzw5ldKggq'
    b'dY23UZQchpF9GJA4Kg2zu+48YCsqkzQSGgu+ETtmYjGpmedvcBoNHw6cgLCFoHuPbbNiOwMT'
    b'YzGyDwFvqNQn8o+iX4aSRSdg19bFqbCqjzIlgCJDkuGWU1dkj1rt1BeZsEMUwR7Kpbbxg8w8'
    b'FJmz5lNE476sa9Ll9WuaUT0a5FoC3hHpmWd1tUCEMisT8JAaPKlt/CAXBPlKpHqCL+u5nJrl'
    b'YOHqXf1TZDY078kCBFAmKkhvskcBNBLaEyMX4nEiwnBgC0ptwVQLCdyGejOB4zVSdrTUNy+G'
    b'1MGfX2T1G3OORDkG2OznIebLjjrXAdOAXYGVwN8IcHePl5xUP9ZPtgY0gfk5lZsQGyxKJR9m'
    b'efU2CVETwBBmDkvvmDqlvLQzX8wOcLijkfDjiCxHudxPmegDDLHny/AxeY3coIdgM7rEXNbl'
    b'qDxSp4I3cYN5GVUaccZjj55DfLnfAq7EZbnGQn+yqRwF9L5s1C4aDT2ssfAp6cKq8F7YvJmG'
    b'vHQPsfYyqNklsyCH6T37N7hnumxXvRejK7SyfK9cduv5J99D9IfYhO95qDeOdgYCb1gmhqb5'
    b'ZwzeWWPOFUjbKpSUU748t98cnVJxj+OQttUada7UGYN3zqjfw//X6xgzANGjEX4DtKByMhJ4'
    b'T6Ohc/P6bds+BuQMVKely9zU8kaBY6BsBXvSsNEm1Xz4XX3XQLwOLM/z9gAMQYZkscbCl9hj'
    b'EzsDD9FWNFziiYug9FWK5DbgIGADSX3K8jtnE+y7CuWXwG7AEkSPlniiqpDd0mrHE1FEj8Zu'
    b'cgOBmwj2XaVR5yw7aPcp4FPgYDz3Ngb0e1XqEtPQtgrgQaAfyL0adWJZHSfVunSSCfF5vgei'
    b'/y6gSos1oP8PNO/KACDWcTQZjquIjW6pl4bPtdoZjurNgCI6U+KJs+TOlZ9oLDQBafsX6Lk+'
    b'kHBKGnryuMyHnF4Gxks8cXRPs0WlrmmJxBNHA+Ntex0Megn4m5J6pwBbQc5j47a3NFo2UerX'
    b'rZd44mzQ6dj1/FatKi/v6NRrBFpQ7YgfG/zcGJMZvPL5dSeAIKrbEMDIzpn1/gJqo1yudOzQ'
    b'xtyA573OgF1eT5d5HIkNkS7FNas1Er4a0dNR30FX3kO8MzJhMtAfILKH1CX+0ROjFSI/H/o5'
    b'jTlHYiSdOyP1zYu1qvxoPO9hYB8w8zXqvI/K7/F4E9GlCAfiuodhz7VIfdNKnTp0EPPWdgTK'
    b'PFb4cMt+eRup6i4W4Y+Fz0D1YdDfZQKMWlV+AJ63FGiQeKLTTQP8M6zLUizknlFBE0bqaBkU'
    b'7yo1TUGoKg+j7ig7YClH5M5M4FYjzj4WCdYG4H0ksIzahsauvAOdOqaI0g0xVKMIoZzqNgLe'
    b'aJnVvKJg41QfUacBCKOBA6R+9VsZ5Y8Ak4MovkMsg7Jaut4EP2rcRfDcbzkr8Z5GnUkgF2Cz'
    b'EFYiLOTjxHwb0G4srFwsNAFPbkLYC8/rS2aYWvkGcHr6v41cjerpaR71IOp8ocqHoFfmZE5Y'
    b'veyPdqtOZhZDnUl4OgGR4YhsQWSezEp0aTyf5gPTwJ0IpA2IsBsKQcSsRF2w16cypOMjE5Kn'
    b'WCFKfU494U2TcgTCgf5/fYzwAcoG4FTS5/MUr7ePb7xHEAah7AUMRTgQYSwWvi+s26O4kHgS'
    b'6DZoX6D1QtBpPtDQ4cMqIwEMLQNXYeHrcCr/w/97BJCkNbCo90J7SB83XQ+6L63B/hJPDJW6'
    b'xHGU9rkAUNCRqTiz1mBARgJKaZ8LpC5xnMQTw2gN9gfdl7VNNV9VFY04+9g7JTlk5Hkssn5k'
    b'2j427DkM2B6UeW+2azS8GnQk/dwRwLv01wo8+gAfFLzrEQ0fg2oVRcnKDgC2gFLVZQNROQqV'
    b'w1EdBjIY2AIsR7w/2E2lKcvHkluWbdOoswYoo8wJQ2IVW5xyrFPcnAnj+7ptsQao2B9xT8N+'
    b'SX6IVZoRfYk2ebGr/EONle2HshS2/wU4OUuf2obNGnVWAqPYVcLAMraXjkRUUFb4qRDee/YX'
    b'ljFYp7GP375gagbqfQ+Rk2gvehfIy17wky+vxuVs0pdncmI6an6qsfA5UtdYCBL7ACgjKXsD'
    b'q0jK3oimygsYwDkbde+FzMyI1FopUMQXGgvfj3FvTOU3ZncQOBXUkIbE8sjuzKLWLoYDbW4V'
    b'7/uAqizxZY4DYLuuxuabjNKq8v75As1Tfoc/zKuaOWwkyeA/ganYXflZlOtQPQPleER+7Efg'
    b'gqhe3InC7/uKVmT9lcIG9PsJgN6DyimoTkDkTOyR7jmgBNXpeOafWu0ML9CBvZhoAnkRR53u'
    b'DMBerfXwXR7USyH4L9gZaLxFqAHPIrIyN7FJo+GFoBPx3J8BP83qdVDjEjY6L2M9/mwKBKqx'
    b'4dFncAMXypzV6S3YpguHxiNiY7RK/mwACBDHpYRAu8UMA+1/IRkcjaEgeICwFmV/kP0w+kfq'
    b'mp7NCrRXlZfjeXehjCep1XQkr1sy5lLU+5bUNryQ13cx16L0RXS+1DZstv6x2PO8G1jUkToR'
    b'c9ZZ18EbKfHm5faeL69gHeRpEk/MK6h8DmkkVI9IJdCAyHxUN2OPd+XYjWmgz7oST46X2Y2r'
    b'NVaxO+qeh9JCyfa7usoT1MtG7ULrFxcCfdD2eVK/br1Wl43ANc/4MsD+sC8DDahswzAA1e9i'
    b'geO67o6LaVnR0DSQO4B2VA6V+salvs/7LrBW4olhBizg6Qe+ATkVQOKJN9H0L3WnRkLTeyKU'
    b'oN6MBQ7KUZ2Ovb0ZAb4PDAT5CCVGsuUAmd24WqvL+qDeEuAmhFm0FT/baVRuSnkprS3PgdwG'
    b'cgMUP6+RESUyq3kFyZZ9UaqxYMRuvrwIolf5eoRR/knS3Nwj48VCM3zjgVCZvv/n4Wdv6NOQ'
    b'maEq+jAqZ4Gco3CTgEp94jcaczyU3yAyR6OhPhJvur0rwTKreY1O5jB7NVXH+I71Zygfg/tq'
    b'XiaBZ04EHWmjd1oEcijSfgEwJ6/zXbypWFBiFTZTYjRm+yTgCf+ucS1QqxcPDeEGD0UZgugu'
    b'qNmCp/9iUOKVnlwq1Gh4Jqr1/ogiUtd4F/hfquKf1sxD1rapRvbuRiNQhprDsrJSI6HpiMwG'
    b'DKIzpa7pjiyBkwkwYIzpzU2iDmX9S4gqN6H8A6NPoaygPjEyax0DIeqsAIYjOhGVccAVIDdK'
    b'vPHqTrrvXG6kYn+MezADEvdkGlVj4UrfeB7KDKlP/KajzjkS5UVgDQMTjtTgpaEbqcFD+D0A'
    b'xrsoQxZS3zQXe6dCUZmlkfJDM+vZI/wcpeuXdxYs74Ysfme0gdmNTwPNCCN8MLODqp19gOFA'
    b'A3VNC1H1b6jrbr0VqLGK3RF3Aco8NpSNTpdXhQ9D9XbsD3depvEsA1P9fz2QMnpOeht3AkmU'
    b'M7OgHkDiTfdhs9aLES97NxTvCyBMSdtvezsYEH/DkH7+jFtsldUjs9jcVOyaFy2f+KcGyY9b'
    b'd0fq1gO7IyxiUPN76XJP67Cu168knrg/q4l1f04H2jEmvaFmGdCPGdirop57ab7g4muxt8wP'
    b'1srQd9LlRi8ENqAysdezUFNgpaagdjsgJRcBKrdK+j6i+AnmyrpeybP0KchHuHpWaib5GbEH'
    b'gaxHi2vyWrhcDgRBH8gMcOWn+Bq5CfBAzs+NH/ihyAd9vnTsQGY1r8HIUQgTcm9CdkuGf/r/'
    b'sjMulY5md9IOUny0SNZn8Stv9koeIPHEdIk3jsq+f+ePR70Hcm826cyKMHAO4IJmBcXyDCi1'
    b'jR+gPAqUIoH8HVc8H/XQcbntpC7xTG8HQ0mfV7FPO31bK8OpMzgI2Z+miD0DK6UaCe2JvRXa'
    b'Qmnra72WWYjspgRG8i+OG68WKEF5OPflkU5uKrmXYm9dTtZoODtrvajtH9h8we8URC96SXLL'
    b'sm0ofwQCBLgR0UMA8HJBxPSmcQjIjb7uD3d3OUdBCgXAsngiI/qBjgHaaG95JasuWjbRP7Ju'
    b'RfXK3LYFDWh9Nbne76JWq8v6pOuswq8CQUxbp/ffFERjzpMadZ7QGeVDOuOzzOaX2HjE6SBn'
    b'AG0EzBPZTN5TWFjpLITTgBZc99dddjujfAhRZyHG+0Aj4TM7ZTTbx2HP5i9nvl1jYSszxx/Q'
    b'NYVu5nd6V47WQXVYZOabuCYnxU39z1jy71SkqAZBdV/gBxR5b2VmtueSzUT1TvZTOTYAF2Rn'
    b'IoDEm5cjMs0u8qxA9Efd3ioPeq8A4xE+Qby3Omf0x2HIXoLaSuZgXaelrEvkO/bkYUzZZPPw'
    b'5DXsI19nSzzxIKRjIO8AnxPw9ioIEeHPgKD3AHA8Rn8ktU1PFOL7ukij4d+DBkmaiM2yL8BT'
    b'XTYM1ywD+mJkdCoOY2PHci/wOcrBnb121P194Wj4AtC7sMexQ1Id+RemT0H4Xwiekvv0Uq6S'
    b'nRn5v0kaG+5A8k/YN2Qek3hisi0v2w81rwB9Ec6RukThtDd6YEAAjToPAj9BaaIoeYTcvrZJ'
    b'Zw7bjUDgNWBPoBXlEUTno+3Pdfe+i+0zfAyit6DyIuL9Xuqa3ujRqDP7qCovx9Mo6MnAJuKJ'
    b'A7vL4bHv0bQdi8okhFOxgO9KXPcQmbPmU51ZESbgvgQMA71X4k3nd9Vfzww4pbyUft4C7NsI'
    b'y2krOlLuXPmJfe0iMAd7v6TjUQfhXZQXUH1U6pteLNhnLDQDldS64iHBirwHxKLOGIThiLbj'
    b'liyS+hVbs+tDD/ubDsCbxBMHFTKgxkJH4TEZkXHYJ6QyHsXQPxDQiMxq3uhPin8Ae6H6ApRM'
    b'7Oy2e4p6/mpHVXl/PF2MfUvgdVz3uzJnzacAFo+Tk1A5wY+QZWQ5yNt4OqPQjW+NlB+K8U4G'
    b'2ZmWQbFMMMLHCNfQAdPPs6kiGe2rndEkOQXMQuobXss1nn1NRO7wdU5RC8oSRBei/EXqm1YC'
    b'NpEyGZzvf85L0eJxuT9YIerluzGhoRhZgv1sP0CCE/NmTWRECabtIFQmgp4LDMVG/S6ReKK+'
    b'x7ImE2CP8K/9I55izNyCiHFn7aNOBLD37uBjVO4D72koeT3vpGER66eBUSgrcM3YzjadXOr9'
    b'y0VV4T3wvPkg+wPNoJMk3lTwEovNDFh/PXAFFkur3mGZo13pGHGqEGZhZ+SvaB18bWdQmx/N'
    b'ewr7Qy9FApOkbnWhZKKC9OXezrKP3vwZe0W+BbhS4onC8QpAo845wL2AoDrTwmNfD/nYpb+2'
    b'6vk+ilSYN+acjXIH9nWl52kN/qi3r498+dfbppSX0k/v8D9TgPsp3j6zs6NVRnwBuomx2Ldd'
    b'QgdgZLhFlVmHp6sY1PSvri5Va8S5yL/XC6KVucBvms9OgLnAT2wBd0FxpLsNoxB95QcY/by8'
    b'O7CBo2aEi/0LewV4s4w4G237RcrlsT6Ze7yfk3w82Y8tpmgT8AwiCyHwTGr91ciQwUjxNUCl'
    b'P6yIxBsLnhz89xbiWHjsM1SmSX3jw19u9DvAgABaFd4bTx8ExtgC/opKlcxuXJ3Hax3zOdjs'
    b'+3agCfsJ5b4j/SHwrh+yHIpN1c0FBdZhM2FD2M2iDYgUmt1aXTYCz9SifM8vegMJnNWbl9oK'
    b'0Y57Q9W+FPQTlNuxWF478Ac8c1Pq1mWaN1KxP3g1iH6flJsibEF5EdH5uGZ+QeNXhisw3gSQ'
    b'47CP3KYwQxd4EmNqcu96+JcDLwfOxRp5M1DDx4nZXT6F0kPa8a/4xip2R71fgp6Fjfq5II/i'
    b'cReDGl/ICuBMKS9lQLKMNt2U8il7LKcGw4bQEIq0L5uCzZkvhPjvfR2LcCHwY6yT3w7cT1vR'
    b'z3oN+nZBX9870pXhCgJ6OfbxRRvnVZoQHgYeY2Bi6Zd9t7SgvMkE2D30bYxMBs6k402Z7Yjc'
    b'i8gtuQjPjqCv/yVzi3ZcAJyFdcBTtBHRF8A8j6tLKUku683j3P7JYS+Ub6NyrJ94nrnxLEd5'
    b'CNW7O3thc0fQf+4tfRAqncMx/AR7eaVAkg8bUZZhdDMqnwGbEFpRSoEBiBEXTlgAAABFSURB'
    b'VO6MMsDPFRxYoP1KkAUYHpLaxlcK1O9w+o8ZMJe0qrwcV49F1P7fHISRKLt22zBFdtNZhvA+'
    b'qktwg4syE5n+U/R/V5DzmuTe7okAAAAASUVORK5CYII=')
getLogoData = Logo.GetData
getLogoImage = Logo.GetImage
getLogoBitmap = Logo.GetBitmap
getLogoIcon = Logo.GetIcon
